### PR TITLE
Added support for CentOS 7 and Libvirt provider

### PR DESCRIPTION
**Pull request by chekolyn**
Hello Alen,

Are you accepting pull requests? I've added support for CentOS 7 and Libvirt provider.

I had to make a few modifications to the environment.sls because they were not working for me.

A little bit more refinement might be needed but things are working.

### CODE REVIEW

**Comment by komljen** [comment]
Hi Sergio,

Thanks for this pull request, looks interesting.
I will test this to see how everything works.

**Comment by komljen** [comment]
Hi Sergio,
Sorry, I totally forgot for this pull request as I didn't have time to work on this repo and to keep it up to date. I started to work again to add multi environment support, ceph rest api, radosgw and mds, etc.

I need to review this again, but there will be a lot of conflicts.

Thanks,
Alen

**Comment by chekolyn** [comment]
Hello @komljen,

Perhaps we can break the pull request in parts; I think I made too many changes when adding support for Vagrant on libvirt. 

The main change was made on this commit https://github.com/chekolyn/ceph-salt/commit/c0e3463b80ba977086bae8518016d1fab4b856a5 

But perhaps with the new Ubuntu 16.04 being on systemd we might need to rethink how I did things there. 

I also asked for a Salt feature to make getting the: conf.admin_keyring  idempotent, but I haven't seen much progress on that: https://github.com/saltstack/salt/issues/27848 

Anyways, what I'm trying to say is that perhaps we should forget about this pull request; and I can help out testing multi environment support step by step. 

What do you think?

**Comment by komljen** [comment]
Sure, I would like to have smaller pull requests which are easier to test and move forward. So, for now we could close this pull request and to focus first on new features which I mentioned, then to add support for multi OS, etc.

**Comment by chekolyn** [comment]
Doing a bit of cleanup I just reset my master to your latest master; made a branch with the old pull request https://github.com/chekolyn/ceph-salt/tree/old-pull just to have some reference if I need to.

Since I work mostly on Vagrant + Libvirt, it might be useful to start with that. What do you think?

**Comment by komljen** [comment]
If it is useful to you why not. I just need to update the readme file to explain how multi environment is working. It is pretty simple.

**Pull request closed without merging**
